### PR TITLE
Add log statements to publisher SDK

### PR DESCRIPTION
**Pull request by KacperKluka**
I've added a few verbose log statements to the `Mapbox` and `CorePublisher` classes to help us debug issues with location updates.

Here's an example of log output from receiving location to sending it:
```
14:38:00.786 [DefaultMapbox] Enhanced location received from Mapbox: Location[null 37.274426,-121.946426 acc=20 et=+18h22m11s583ms alt=0.0 vel=54.06 bear=10.857853]
14:38:00.786 [DefaultCorePublisher] Enhanced location received: Location(latitude=37.2744264173863, longitude=-121.94642617300786, altitude=0.0, accuracy=20.0, bearing=10.857853, speed=54.06, time=1637761080786)
14:38:00.786 [DefaultCorePublisher] Enhanced location changed event received Location(latitude=37.2744264173863, longitude=-121.94642617300786, altitude=0.0, accuracy=20.0, bearing=10.857853, speed=54.06, time=1637761080786)
14:38:00.786 [DefaultCorePublisher] Processing enhanced location for trackable: xxxxx. Location(latitude=37.2744264173863, longitude=-121.94642617300786, altitude=0.0, accuracy=20.0, bearing=10.857853, speed=54.06, time=1637761080786)
14:38:00.787 [DefaultCorePublisher] Trackable: xxxxx will send enhanced location Location(latitude=37.2744264173863, longitude=-121.94642617300786, altitude=0.0, accuracy=20.0, bearing=10.857853, speed=54.06, time=1637761080786)
14:38:00.788 sendEnhancedLocationMessage: publishing: {"intermediateLocations":[{"geometry":{"coordinates":[-121.94654799999999,37.273921,0.0],"type":"Point"},"properties":{"accuracyHorizontal":0.0,"bearing":10.431928,"speed":0.0,"time":1.637761080128E9},"type":"Feature"}],"location":{"geometry":{"coordinates":[-121.94642617300786,37.2744264173863,0.0],"type":"Point"},"properties":{"accuracyHorizontal":20.0,"bearing":10.857853,"speed":54.06,"time":1.637761080786E9},"type":"Feature"},"skippedLocations":[],"type":"PREDICTED"}

```

### CODE REVIEW

**Review by QuintinWillison — APPROVED** [review]
I don't want to block us landing this PR based on these observations, but I do want to make the observations as it may be a good idea to add them to our issues backlog for future work:

1. I can see what you're aiming to do with the `createLoggingTag` utility function, but it actually ends up with very repetitive code - with, effectively, two APIs required for every call to log - being: (1) method `v` on `logHandler`; and (2) use val `TAG`. I would prefer to see `TAG` implicit in each call to log - i.e. have an intermediary to replace `TAG` - perhaps called `LOG` on which you call `v` to automatically use the `TAG` (i.e. inject at one point in the file). This, perhaps, intersects with #326 - being more the pattern you would observe with SLF4J, for example.
2. Threading. The implication of the current design means that the app developer's implementation of log handler is going to get called from multiple threads. Elsewhere in this SDK we make a promise to call on the main thread / coroutine scope. So, it feels to me like we should be able to make similar promises here. Again, intersects with #326 as SLF4J implementations will likely do this for free.

**Comment by AndyNicks** [comment]
Does the logHandler?.v() function add a timestamp to a log?

**Comment by QuintinWillison** [comment]
So, I guess, in interim - regarding threading - it would be worth ensuring that the log handler interface clearly documents that it can be called from multiple threads.

**Comment by KacperKluka** [comment]
> Does the logHandler?.v() function add a timestamp to a log?

@AndyNicks No, it doesn't, should we create an issue for that? :wink: 

---

> So, I guess, in interim - regarding threading - it would be worth ensuring that the log handler interface clearly documents that it can be called from multiple threads.

@QuintinWillison I think the info is already there in the interface docs :wink: 

```kotlin
/**
 * Gets called when a log message is sent from the SDK.
 * This method is called synchronously and can be called from any thread.
 * Don't run blocking code in this method as this can cause the SDK to malfunction.
 *
 * @param level The importance level of the message.
 * @param message The message text.
 * @param throwable Optional error object.
 */
fun logMessage(level: LogLevel, message: String, throwable: Throwable? = null)
```

**Comment by QuintinWillison** [comment]
Perfect, thanks for clarifying @KacperKluka - I hadn't gone to depth of checking the docs myself this morning because I was short of time.

**Comment by AndyNicks** [comment]
Yes please

**Review by AndyNicks — APPROVED** [review]

**Review by ikbalkaya — APPROVED** [review]
Looks good to me

**Comment by KacperKluka** [comment]
I've created the issue about adding timestamps to logs: https://github.com/ably/ably-asset-tracking-android/issues/530

**Pull request merged**
