### PR TITLE
Add a button for centering the camera on the marker on the map

### PR DESCRIPTION
**Pull request by KacperKluka**
I added a button that centers the camera on the marker on the map. The button is displayed only when a trackable is actively tracked.
Screenshot_20210406-150816_Subscriber

### CODE REVIEW

**Review by owenpearson — APPROVED** [review]
Code changes look fine to me. I'm unsure about the icon used here though. If I saw that icon on a map I would generally assume that it would centre on _my_ location, rather than the location of the thing being tracked. I wonder if we should use a different icon here? @kavalerov do you have any thoughts on this?

**Comment by kavalerov** [comment]
I just added a comment on the issue - lets just centre on the marker all the time, and remove button - this should showcase locating the asset, so user doesn't really need to be able to scroll around the map.

**Comment by kavalerov** [comment]
@KacperKluka this PR will later be updated with autocentering, right?

**Comment by KacperKluka** [comment]
@kavalerov yes, that's my plan but I have other priorities right now so don't know when I'll work on this. So we can either land it as it is or remove this PR for now and I'll add that autocentering in the future :wink:

**Comment by KacperKluka** [comment]
I'm closing that because we've implemented a better solution with https://github.com/ably/ably-asset-tracking-android/pull/289

**Pull request closed without merging**
